# Generated by Django 5.1.6 on 2025-03-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cpu_gpu_motherboard_psu_ram_storage_delete_component'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cpu',
            table='CPUs',
        ),
        migrations.AlterModelTable(
            name='gpu',
            table='GPUs',
        ),
        migrations.AlterModelTable(
            name='motherboard',
            table='Motherboards',
        ),
        migrations.AlterModelTable(
            name='psu',
            table='PSUs',
        ),
        migrations.AlterModelTable(
            name='ram',
            table='RAMs',
        ),
        migrations.AlterModelTable(
            name='storage',
            table='Storages',
        ),
    ]
