# Generated by Django 5.1.6 on 2025-03-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storage',
            table='Storage',
        ),
    ]
