# Generated by Django 5.1.6 on 2025-03-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_budgetpcbuild_enthusiastpcbuild_gamingpcbuild_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamingPCBuild',
            new_name='budgetbuild',
        ),
        migrations.RenameModel(
            old_name='ProfessionalPCBuild',
            new_name='enthusiast',
        ),
        migrations.RenameModel(
            old_name='WorkstationPCBuild',
            new_name='gamingbuilds',
        ),
        migrations.RenameModel(
            old_name='BudgetPCBuild',
            new_name='professional',
        ),
        migrations.RenameModel(
            old_name='EnthusiastPCBuild',
            new_name='workstations',
        ),
        migrations.AlterModelTable(
            name='budgetbuild',
            table='budgetbuild',
        ),
        migrations.AlterModelTable(
            name='enthusiast',
            table='enthusiast',
        ),
        migrations.AlterModelTable(
            name='gamingbuilds',
            table='gamingbuilds',
        ),
        migrations.AlterModelTable(
            name='professional',
            table='professional',
        ),
        migrations.AlterModelTable(
            name='workstations',
            table='workstations',
        ),
    ]
