# Generated by Django 5.1.6 on 2025-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_gamingpcbuild_budgetbuild_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamingbuilds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('psu', models.CharField(max_length=100)),
                ('cabinet', models.CharField(max_length=100)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'gamingbuilds',
            },
        ),
        migrations.DeleteModel(
            name='gamingbuildss',
        ),
    ]
