# Generated by Django 5.1.6 on 2025-03-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gamingbuilds_delete_gamingbuildss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetbuild',
            name='cabinet',
        ),
    ]
