# Generated by Django 5.1.6 on 2025-03-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_budgetbuild_cabinet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enthusiast',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='gamingbuilds',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='workstations',
            name='cabinet',
        ),
    ]
